// BURGER BUILDING //

export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

// BURGER PURCHASING //

export const PURCHASE_BURGER_START = "PURCGASE_BURGER_START";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER = "PURCHASE_BURGER";
export const PURCHASE_BURGER_FAILED = "PURCGASE_BURGER_FAILED";
export const PURCHASE_BURGER_INIT = "PURCHASE_BURGER_INIT";
export const FETCH_ORDERS = "FETCH_ORDERS";

// FETCH ORDERS //

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

// AUTHENTICATION //

export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_USER = "AUTH_USER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_CHECK_EXP_STATE = "AUTH_CHECK_EXP_STATE";
export const AUTH_INIT_LOGOUT = "AUTH_INIT_LOGOUT";
export const AUTH_CHECK_SESSION = "AUTH_CHECK_SESSION";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// BURGER STATE  WHILE PURCHASING //

export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";
